services:
  app_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    working_dir: /app/frontend/filmore
    user: node  
    volumes:
      - ./filmore:/app/frontend/filmore  # Mount the current directory to the container
    ports:
      - "5173:5173"      # Expose the port for the application
    networks:
      - local

    command: >
      sh -c "if [ ! -d node_modules ]; then npm install; fi && npm run dev"

networks:
  local:
    driver: bridge  