name: Sonar Cloud frontend Scan
on:
	push:
		branches:
			- main
	pull_request:
		branches:
			- main
jobs:
	sonarcloud:
		name: SonarCloud
		runs-on: ubuntu-latest
		steps:
		    - name: Checkout to main branch
			  uses: actions/checkout@v3
			  with:
				fetch-depth: 0

			- name: Setup nodejs
			  uses: actions/setup-node@v3
			  with:
				node-version: '18'

			- name: Install npm dependencies
			  run: npm install

			- name: Build frontend
			  run: npm run build

			- name: SonarCloud Scan
				env:
					SONAR_TOKEN: ${{ secrets.FRONTEND_SONAR_TOKEN }}
			  run: |
			  	   npx sonar-scanner \
				   -Dsonar.organization=univalle-software-development \
				   -Dsonar.projectKey=univalle-software-development_frontend \
				   -Dsonar.sources=./src \
				   -Dsonar.exclusions=**/node_modules/** \
				   -Dsonar.host.url=https://sonarcloud.io \
				   -Dsonar.javascript.node.maxspace=4096 \
				   -Dsonar.tests=./src/test \
                   -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
				   -Dsonar.genericCoverageReportPaths=coverage/coverage-final.json
				   
				   
