name: Vercel Staging Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - staging  
jobs:
  Deploy-staging:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
     
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information (Production)
        run: vercel pull --yes --environment=staging --token=${{ secrets.VERCEL_TOKEN }}      

      - name: Build Project Artifacts
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}