name: Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Wait for quality gate
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Quality Gate'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
     
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        working-directory: filmore
        run: vercel pull --yes --environment=staging --token=${{ secrets.VERCEL_TOKEN }}      

      - name: Build Project Artifacts
        working-directory: filmore
        run: vercel build --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: filmore
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
